### ISSUE TITLE
Use a Google Cloud bucket to handle data

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/decision_tree_course#12]
## Tasks

- [x] create a GCS project EEIA and a bucket per repo: for instance bucket `decision_tree_course` for this repo
- [x] get the credentials to allow access to data stored via GCS Python API
- [x] build a package to handle automatic reading of data stored
