### ISSUE TITLE
Implement the CI

### ISSUE THREAD

**Issue by akouete-kpakpo** [ML-for-B-E/decision_tree_course#3]
## Tasks

- [x] check that the repository contains the following folders: notebooks, figures, requirements, src, tests, .gitignore, README.md, setup.py
- [ ] check that all the tests run 
   - [x] functions
   - [ ] notebooks
- [x] check that the code is 3.8 compatible
- [ ] check that there is no .csv (we will implement a proper way to load data using Dropbox), .png (except in the folder figures)
- [ ] check black compatibility
